package msg

import (
	"encoding/json"
	"reflect"
	"strings"
	"time"

	"ngrok/policy"
)

var TypeMap map[string]reflect.Type

func init() {
	TypeMap = make(map[string]reflect.Type)

	t := func(obj interface{}) reflect.Type { return reflect.TypeOf(obj).Elem() }
	TypeMap["Auth"] = t((*Auth)(nil))
	TypeMap["AuthResp"] = t((*AuthResp)(nil))
	TypeMap["ReqTunnel"] = t((*ReqTunnel)(nil))
	TypeMap["NewTunnel"] = t((*NewTunnel)(nil))
	TypeMap["RegMux"] = t((*RegMux)(nil))
	TypeMap["RegProxy"] = t((*RegProxy)(nil))
	TypeMap["ReqProxy"] = t((*ReqProxy)(nil))
	TypeMap["StartProxy"] = t((*StartProxy)(nil))
	TypeMap["Ping"] = t((*Ping)(nil))
	TypeMap["Pong"] = t((*Pong)(nil))
}

type Message interface{}

type Envelope struct {
	Type    string
	Payload json.RawMessage
}

// When a client opens a new control channel to the server
// it must start by sending an Auth message.
type Auth struct {
	Version   string // protocol version
	MmVersion string // major/minor software version (informational only)
	User      string
	Password  string
	OS        string
	Arch      string
	ClientId  string // empty for new sessions
	Caps      []string

	// Secret is the session secret of the ClientId being resumed, as handed
	// out in AuthResp.Secret when that id was first assigned.
	//
	// The field is additive and its absence fails closed. A client that sends
	// a ClientId it cannot prove -- an old client that predates this field, or
	// a caller that guessed an id -- is refused: the server never hands a
	// session (its tunnels, its proxy pool, its mux session) to a connection
	// that has not proved it owns the id. A client with no secret proves
	// nothing and must ask for a new session instead, by sending an empty
	// ClientId.
	//
	// Mixed deployments therefore have a one-way requirement: the server may
	// not be upgraded ahead of the clients that reconnect to it, because a
	// pre-secret client that reconnects with its old id is refused and exits.
	// Upgrade the clients first, or accept that their next reconnect starts a
	// new session.
	Secret string
}

// A server responds to an Auth message with an
// AuthResp message over the control channel.
//
// If Error is not the empty string
// the server has indicated it will not accept
// the new session and will close the connection.
//
// The server response includes a unique ClientId
// that is used to associate and authenticate future
// proxy connections via the same field in RegProxy messages.
type AuthResp struct {
	Version   string
	MmVersion string
	ClientId  string
	Error     string
	Caps      []string

	// Secret is the session secret that goes with ClientId: the bearer proof
	// that a later connection claiming this id is the same client. It is
	// generated by the server (crypto/rand) when the id is assigned, is never
	// logged and never appears in telemetry, and the client must present it in
	// three places -- the Secret field of Auth when resuming this ClientId, of
	// RegProxy, and of RegMux. An empty Secret is a server that does not
	// implement this (or a refused auth), and a client must never resume an id
	// without one.
	Secret string
}

// A client sends this message to the server over the control channel
// to request a new tunnel be opened on the client's behalf.
// ReqId is a random number set by the client that it can pull
// from future NewTunnel's to correlate then to the requesting ReqTunnel.
type ReqTunnel struct {
	ReqId    string
	Protocol string

	// http only
	Hostname  string
	Subdomain string
	HttpAuth  string

	// tcp only
	RemotePort uint16

	// Binding selects the kind of endpoint to create. "" (the zero value, so
	// old clients keep working) is a public endpoint reachable through the
	// public listeners; "internal" is a private endpoint that only forward_to
	// from an endpoint of the same account can reach.
	Binding string

	// Pooling allows several agents to register the same url and share the
	// traffic between them, round-robin per connection.
	Pooling bool

	// ForwardTo routes this endpoint's traffic to an internal endpoint
	// ("https://svc.internal") instead of to this client's own upstream.
	ForwardTo string

	// TrafficPolicy is the endpoint's edge policy, enforced by the server
	// (SPEC 3.3). Nil means the endpoint has none, which is what every client
	// that does not configure one sends: the field is additive, so an old
	// client and a policy-free endpoint take exactly the path they took
	// before. The server compiles it once, when the tunnel is registered.
	TrafficPolicy *policy.TrafficPolicy

	// TLSTermination selects who terminates public TLS for an https endpoint
	// (SPEC-CLUSTER5 5.1). "" (the zero value, so an old-style message decodes
	// to it and every pre-existing tunnel keeps its behavior) is
	// TLSTerminationEdge: the server terminates with its own certificate, as
	// it always has. TLSTerminationAgent ("agent") is zero-knowledge TLS: the
	// server routes by SNI and passes the TLS bytes through untouched, and the
	// certificate, the keys and the plaintext all live on the agent side --
	// the server never sees either.
	//
	// The field is only meaningful for the https leg of the request. Because
	// the server splits a multi-leg request ("http+https") into one
	// registration per leg while the field rides on the request as a whole,
	// the server honors it on the https leg and ignores it on the others;
	// see server/tunnel.go validateRequest.
	TLSTermination string
}

// When the server opens a new tunnel on behalf of
// a client, it sends a NewTunnel message to notify the client.
// ReqId is the ReqId from the corresponding ReqTunnel message.
//
// A client may receive *multiple* NewTunnel messages from a single
// ReqTunnel. (ex. A client opens an https tunnel and the server
// chooses to open an http tunnel of the same name as well)
type NewTunnel struct {
	ReqId    string
	Url      string
	Protocol string
	Error    string

	// TLSTermination echoes the termination mode the server actually
	// registered the endpoint under, after normalize-and-refuse validation.
	// It exists so a client that asked for agent termination can tell, at
	// establishment time, whether it got it: a server from before this field
	// decodes nothing here and an old-server client mispairing registers
	// "successfully" but terminates nothing -- so the client treats a
	// requested-but-not-echoed agent mode as a fatal error rather than serve
	// an endpoint whose TLS the server holds and its own terminator expects.
	TLSTermination string
}

// When the server wants to initiate a new tunneled connection, it sends
// this message over the control channel to the client. When a client receives
// this message, it must initiate a new proxy connection to the server.
type ReqProxy struct {
}

// After authenticating with a server whose AuthResp advertises the "proxy-mux"
// capability, a client may open one multiplexed connection to the server and
// send this message over it as its first message, naming the control session
// (ClientId) the connection belongs to. Every proxy connection for that client
// then arrives as a stream on this connection, each of which still starts with
// the RegProxy message it always had; the server replies to a RegMux it cannot
// attach to a control session by closing the connection.
type RegMux struct {
	ClientId string

	// Secret is the session secret of ClientId (AuthResp.Secret). A mux conn is
	// a second door into an existing session, so it is authenticated exactly
	// like a proxy conn is: naming an id is not enough, and a conn that cannot
	// prove the id is closed without being attached. An old client that does
	// not send it is refused -- see Auth.Secret on the upgrade requirement.
	Secret string
}

// After a client receives a ReqProxy message, it opens a new
// connection to the server and sends a RegProxy message.
type RegProxy struct {
	ClientId string

	// Secret is the session secret of ClientId (AuthResp.Secret). This is the
	// authentication of the proxy path: the ClientId alone is a public
	// identifier -- it is logged, it is cached, it is in every admin snapshot
	// -- and it may not be sufficient to be handed another session's traffic.
	// A RegProxy without a matching secret is closed and never pooled. An old
	// client that does not send it is refused -- this is deliberate, and it
	// means a server upgrade requires the clients to be upgraded with it.
	Secret string
}

// This message is sent by the server to the client over a *proxy* connection before it
// begins to send the bytes of the proxied request.
type StartProxy struct {
	Url        string // URL of the tunnel this connection connection is being proxied for
	ClientAddr string // Network address of the client initiating the connection to the tunnel
}

// A client or server may send this message periodically over
// the control channel to request that the remote side acknowledge
// its connection is still alive. The remote side must respond with a Pong.
type Ping struct {
}

// Sent by a client or server over the control channel to indicate
// it received a Ping.
type Pong struct {
}

// ---------------------------------------------------------------------------
// Wire vocabulary shared by both binaries
//
// These strings are part of the protocol, not of either end's configuration:
// ngrokd and ngrok emit and compare the same values, so a constant that lives
// in one binary with a copy spelled out in the other is a copy that can drift
// with nothing to catch it -- both halves still compile, and the two ends stop
// agreeing on the wire. They live here, next to the messages that carry them.
// ---------------------------------------------------------------------------

const (
	// MuxCapability is the AuthResp capability that tells a client it may carry
	// every proxy connection as a stream on one long-lived multiplexed
	// connection (SPEC cluster 3, 3.1). It gates nothing on the server side --
	// a client that opens a mux conn states what it wants with RegMux -- but a
	// client that never sees the cap keeps dialing one connection per proxy
	// connection, which is exactly what a mixed-version deployment needs.
	MuxCapability = "proxy-mux"

	// QuicCapability is the AuthResp capability that tells a client the server
	// is running a QUIC listener (SPEC cluster 7), so its proxy streams may
	// ride a QUIC session -- where a lost packet stalls only the stream it
	// belongs to -- instead of the TCP+smux carrier. Unlike proxy-mux it gates
	// something on the server side: the listener is opt-in (-quicAddr), so the
	// cap is advertised only while it is up, and a client that never sees it
	// keeps the transport it has always used, which is exactly what a
	// mixed-version deployment needs.
	QuicCapability = "proxy-quic"

	// QuicALPN is the application protocol the QUIC transport requires in its
	// TLS handshake, both directions. Like the rest of the wire vocabulary it
	// lives here and nowhere else: the ALPN check is what refuses
	// cross-protocol misdirection (a QUIC client hitting a TCP-only port, or
	// the reverse) at the handshake, and a mismatch is a refused handshake --
	// which the client treats as its cue to fall back to the smux carrier,
	// so even a version skew fails safe. But fail-safe drift is still drift;
	// one spelling is one spelling.
	QuicALPN = "ngrok"

	// BindingPublic and BindingInternal are the accepted values of
	// ReqTunnel.Binding. The empty string is what the wire carries for a public
	// endpoint, so "public" is a configuration spelling only: the client
	// normalizes it to "" at load time, and the server accepts exactly these
	// two values and no others (server/tunnel.go).
	BindingPublic   = ""
	BindingInternal = "internal"

	// InternalSuffix is the reserved namespace for internal endpoints: an
	// endpoint's hostname must end in it to be internal, and nothing outside it
	// can be registered as internal. Both ends need it -- the client to refuse
	// the oxymoron of a public endpoint named .internal before it is sent, the
	// server to enforce the namespace as the authority (SPEC 3.2).
	InternalSuffix = ".internal"

	// Protocol names, as they appear in ReqTunnel.Protocol and
	// NewTunnel.Protocol, as the keys of a config file's proto section, and as
	// the names of the public listeners.
	ProtoHTTP  = "http"
	ProtoHTTPS = "https"
	ProtoTCP   = "tcp"
	ProtoUDP   = "udp"

	// ProtoHTTPPlusHTTPS is the client's spelling for one endpoint with both
	// HTTP legs ("ngrok http+https 8080"). It exists in the client's
	// configuration and in the ReqTunnel it builds: the server splits the field
	// on "+" and registers one endpoint per leg, so a server never carries this
	// spelling in a Tunnel.
	ProtoHTTPPlusHTTPS = "http+https"

	// TLSTerminationEdge and TLSTerminationAgent are the accepted values of
	// ReqTunnel.TLSTermination (SPEC-CLUSTER5 5.1). The empty string is what
	// the wire carries for a server-terminated endpoint, so "edge" is a
	// configuration spelling only: the client normalizes it to "" at load
	// time, and the server accepts exactly these two values and no others
	// (server/tunnel.go). A value outside the pair is a refused registration,
	// not a silent fallback to edge termination -- falling back would turn
	// every spelling mistake into an endpoint where the server holds the
	// certificate the operator believes the agent holds.
	TLSTerminationEdge  = ""
	TLSTerminationAgent = "agent"
)

// IsHTTP reports whether one protocol name -- a single leg, as it appears on
// the wire and as a key of the listeners map -- is served over HTTP.
func IsHTTP(proto string) bool {
	return proto == ProtoHTTP || proto == ProtoHTTPS
}

// ---------------------------------------------------------------------------
// Shared timing values
//
// These durations are agreement, not the policy of one end: both binaries
// expire the same flows and keep the same carrier sessions alive, and a value
// one end holds and the other does not share is a disagreement waiting for a
// network partition to be noticed. Like the wire vocabulary above, they live
// here, next to the messages whose transports they keep alive, so each end
// derives its own (possibly private) constants from one declaration rather
// than spelling the same duration twice.
//
// Not every usage site is unified yet. The client side derives from these
// (client/model.go); the server still spells its copies as literals -- the
// next reader finishing the unification wants msg/shared_timeouts_test.go,
// which pins the values here and names the server's literal sites by file:line.
// ---------------------------------------------------------------------------

const (
	// UdpIdleTimeout is how long a udp flow may sit with no traffic in either
	// direction before either end closes it (SPEC-CLUSTER8 3.2). The two ends
	// must agree on it because either side's expiry tears down the flow's
	// other half through the proxy conn close, and a client that tolerates a
	// longer silence than its server would only ever see the server's clock.
	UdpIdleTimeout = 30 * time.Second

	// CarrierKeepAlive is how often a mux carrier (smux and QUIC alike) pings
	// an idle peer (SPEC-CLUSTER7 5). The keepalive is load-bearing: it is
	// what turns a peer that vanished silently into a dead session -- and
	// therefore into a reconnected one -- without waiting for the next proxy
	// stream to be attempted.
	CarrierKeepAlive = 10 * time.Second

	// CarrierIdleTimeout is how long a carrier session may see no traffic at
	// all -- the keepalives above included -- before it is given up on
	// (SPEC-CLUSTER7 5). It bounds CarrierKeepAlive: a peer that stopped
	// answering is declared dead after seeing this much silence.
	CarrierIdleTimeout = 30 * time.Second
)

// IsHTTPOnly reports whether every leg of a protocol field is served over
// HTTP. The field may be the "+"-joined combination the client builds, so this
// splits it the way the server does before answering. The empty string is not
// an HTTP protocol: no registration carries one, and the two callers in the
// client both refuse a tunnel that names no protocol at all.
func IsHTTPOnly(proto string) bool {
	if proto == "" {
		return false
	}

	for _, p := range strings.Split(proto, "+") {
		if !IsHTTP(p) {
			return false
		}
	}

	return true
}
