FROM golang:1.21-alpine AS build
WORKDIR /src
COPY . .
RUN apk add --no-cache make git && \
    make server

FROM alpine:3.20
RUN adduser -D -u 10001 ngrok
USER ngrok
WORKDIR /home/ngrok
COPY --from=build /src/bin/ngrokd /usr/local/bin/ngrokd
ENTRYPOINT ["ngrokd"]

