package server

// Tests for the SNI peek and the https listener's routing split
// (SPEC-CLUSTER5 5.2, testing strategy 7-A).
//
// The ClientHello fixtures are generated by a real crypto/tls client at test
// time rather than checked in as golden files: a checked-in hello pins one Go
// release's extension set, and the parser's job is to skip whatever appears,
// not to recognize one emitter. What IS pinned by hand (buildClientHello) is
// the exact wire arithmetic -- vector widths, extension framing, the
// server_name list -- so a parser regression cannot hide behind a
// regenerated fixture.
//
// The routing tests run the real httpsConnHandler on one end of a loopback
// pair: assertions are about bytes on a socket, not about calls into a mock.
// The fixtures come from registry_v2_test.go / policy_test.go, for the reason
// documented there (conn.Wrap only understands *net.TCPConn, so net.Pipe is
// reserved for the TLS-level tests, which need no conn.Conn).

import (
	"bufio"
	"bytes"
	"crypto/tls"
	"encoding/binary"
	"errors"
	"fmt"
	"io"
	"net"
	"net/http"
	"strings"
	"testing"
	"time"

	"ngrok/conn"
	"ngrok/msg"
	"ngrok/policy"
)

// ---------------------------------------------------------------------------
// ClientHello fixtures

// tlsClientConfig returns the config of the fake public visitor: it names
// serverName via SNI, accepts the server's snakeoil certificate, and speaks
// the oldest shape of the protocol by default (the 1.3 shape is requested
// explicitly where it is the point).
func tlsClientConfig(serverName string) *tls.Config {
	return &tls.Config{
		ServerName:         serverName,
		InsecureSkipVerify: true, // the snakeoil cert is not for this name
		MaxVersion:         tls.VersionTLS12,
	}
}

// startTLSClient begins a real TLS client handshake over one end of a pipe
// and returns the client end (a live *tls.Conn the test drives) and the raw
// server end, where the hello lands. The handshake stalls until the test
// reads the hello, which is exactly the pause the parser tests need.
func startTLSClient(t *testing.T, cfg *tls.Config) (*tls.Conn, net.Conn) {
	t.Helper()

	rawClient, rawServer := net.Pipe()
	t.Cleanup(func() { rawClient.Close(); rawServer.Close() })

	return tls.Client(rawClient, cfg), rawServer
}

// captureClientHello runs a real TLS client handshake attempt far enough to
// put its ClientHello on the wire, and returns those bytes: the golden
// fixtures the parser is tested against.
func captureClientHello(t *testing.T, cfg *tls.Config) []byte {
	t.Helper()

	client, rawServer := startTLSClient(t, cfg)
	go func() { _ = client.Handshake() }() // the hello is only written once the handshake starts
	hello := readOneRecord(t, rawServer)
	rawServer.Close() // the client's handshake fails; nothing leaks
	return hello
}

// readOneRecord reads exactly one TLS record off r.
func readOneRecord(t *testing.T, r io.Reader) []byte {
	t.Helper()

	if deadline, ok := r.(interface{ SetDeadline(time.Time) error }); ok {
		if err := deadline.SetDeadline(time.Now().Add(publicTimeout)); err != nil {
			t.Fatalf("failed to set a read deadline: %v", err)
		}
	}

	var header [5]byte
	if _, err := io.ReadFull(r, header[:]); err != nil {
		t.Fatalf("reading the record header of a ClientHello: %v", err)
	}
	recLen := int(binary.BigEndian.Uint16(header[3:5]))

	hello := make([]byte, 5+recLen)
	copy(hello, header[:])
	if _, err := io.ReadFull(r, hello[5:]); err != nil {
		t.Fatalf("reading the body of a ClientHello record: %v", err)
	}
	return hello
}

// fragmentClientHello repacks one hello's records so the same bytes travel in
// records no larger than chunk bytes -- the shape a middlebox or a tiny-MTU
// stack produces and the reason the parser walks records at all.
func fragmentClientHello(t *testing.T, hello []byte, chunk int) []byte {
	t.Helper()

	if chunk <= 0 || chunk > 0xFFFF {
		t.Fatalf("bad fragment size %d", chunk)
	}

	var out bytes.Buffer
	body := hello[5:] // the first record header is replaced below
	first := true
	for len(body) > 0 {
		n := chunk
		if n > len(body) {
			n = len(body)
		}
		if first {
			// keep the original legacy_version from the first record header
			out.Write([]byte{tlsRecordHandshake, hello[1], hello[2], byte(n >> 8), byte(n)})
			first = false
		} else {
			out.Write([]byte{tlsRecordHandshake, 0x03, 0x03, byte(n >> 8), byte(n)})
		}
		out.Write(body[:n])
		body = body[n:]
	}
	return out.Bytes()
}

// buildClientHello hand-assembles one minimal ClientHello naming sniName (no
// extension block at all when the name is empty). This is the fixture that
// pins the parser's arithmetic to the RFC's, independent of whatever
// extensions the Go release of the day emits.
func buildClientHello(t *testing.T, sniName string, extraExtType uint16, extraExtData []byte) []byte {
	t.Helper()

	var extensions bytes.Buffer
	if sniName != "" {
		var list bytes.Buffer
		list.WriteByte(tlsServerNameHostName) // name_type: host_name
		list.Write([]byte{byte(len(sniName) >> 8), byte(len(sniName))})
		list.WriteString(sniName)

		var ext bytes.Buffer
		ext.Write([]byte{byte(list.Len() >> 8), byte(list.Len())})
		ext.Write(list.Bytes())

		extensions.Write([]byte{0x00, 0x00}) // server_name
		extensions.Write([]byte{byte(ext.Len() >> 8), byte(ext.Len())})
		extensions.Write(ext.Bytes())
	}
	if extraExtData != nil {
		extensions.Write([]byte{byte(extraExtType >> 8), byte(extraExtType)})
		extensions.Write([]byte{byte(len(extraExtData) >> 8), byte(len(extraExtData))})
		extensions.Write(extraExtData)
	}

	var body bytes.Buffer
	body.Write([]byte{0x03, 0x03})             // legacy_version
	body.Write(bytes.Repeat([]byte{0xAB}, 32)) // random
	body.WriteByte(0x00)                       // session_id: empty
	body.Write([]byte{0x00, 0x02, 0x13, 0x01}) // cipher_suites
	body.WriteByte(0x01)                       // compression_methods
	body.WriteByte(0x00)                       // compression: null
	body.Write([]byte{byte(extensions.Len() >> 8), byte(extensions.Len())})
	body.Write(extensions.Bytes())

	hs := make([]byte, 0, tlsHandshakeHeaderSize+body.Len())
	hs = append(hs, tlsHandshakeClientHello)
	hs = append(hs, byte(body.Len()>>16), byte(body.Len()>>8), byte(body.Len()))
	hs = append(hs, body.Bytes()...)

	if len(hs)+5 > 0xFFFF {
		t.Fatalf("hand-built hello too large for one record: %d", len(hs))
	}

	rec := make([]byte, 0, len(hs)+5)
	rec = append(rec, tlsRecordHandshake, 0x03, 0x01)
	rec = append(rec, byte(len(hs)>>8), byte(len(hs)))
	rec = append(rec, hs...)
	return rec
}

// ---------------------------------------------------------------------------
// 7-A: the parser

func TestSNIReadsSingleRecordHello(t *testing.T) {
	hello := captureClientHello(t, tlsClientConfig("single.test"))

	sni, peeked, err := readClientHelloSNI(bytes.NewReader(hello), maxHeadBytes)
	if err != nil {
		t.Fatalf("readClientHelloSNI: %v", err)
	}
	if sni != "single.test" {
		t.Fatalf("parsed SNI %q, want %q", sni, "single.test")
	}
	// The replay contract: everything read is returned, nothing more.
	if !bytes.Equal(peeked, hello) {
		t.Fatalf("peeked %d bytes, consumed %d -- the replay would corrupt the stream", len(hello), len(peeked))
	}
}

func TestSNIReadsTLS12AndTLS13Shapes(t *testing.T) {
	for _, version := range []uint16{tls.VersionTLS12, tls.VersionTLS13} {
		cfg := tlsClientConfig(fmt.Sprintf("v%x.test", version))
		cfg.MinVersion = version
		cfg.MaxVersion = version

		hello := captureClientHello(t, cfg)
		sni, _, err := readClientHelloSNI(bytes.NewReader(hello), maxHeadBytes)
		if err != nil {
			t.Fatalf("TLS 0x%x: readClientHelloSNI: %v", version, err)
		}
		if want := fmt.Sprintf("v%x.test", version); sni != want {
			t.Fatalf("TLS 0x%x: parsed SNI %q, want %q", version, sni, want)
		}
	}
}

func TestSNIReportsAbsentWhenHelloCarriesNoServerName(t *testing.T) {
	// An IP-literal visitor: Go omits the server_name extension entirely
	// when the config names no server.
	hello := captureClientHello(t, &tls.Config{InsecureSkipVerify: true, MaxVersion: tls.VersionTLS12})

	sni, peeked, err := readClientHelloSNI(bytes.NewReader(hello), maxHeadBytes)
	if !errors.Is(err, ErrSNIAbsent) {
		t.Fatalf("want ErrSNIAbsent, got %v (sni %q)", err, sni)
	}
	if sni != "" {
		t.Fatalf("an absent SNI must come back empty, got %q", sni)
	}
	if !bytes.Equal(peeked, hello) {
		t.Fatal("an absent SNI must still replay every consumed byte")
	}
}

func TestSNIReassemblesFragmentedHello(t *testing.T) {
	hello := captureClientHello(t, tlsClientConfig("fragmented.test"))

	for _, chunk := range []int{1, 2, 7, 64, len(hello) - 6} {
		fragmented := fragmentClientHello(t, hello, chunk)
		sni, peeked, err := readClientHelloSNI(bytes.NewReader(fragmented), maxHeadBytes)
		if err != nil {
			t.Fatalf("chunk %d: readClientHelloSNI: %v", chunk, err)
		}
		if sni != "fragmented.test" {
			t.Fatalf("chunk %d: parsed SNI %q, want %q", chunk, sni, "fragmented.test")
		}
		if !bytes.Equal(peeked, fragmented) {
			t.Fatalf("chunk %d: peeked %d bytes, consumed %d", chunk, len(fragmented), len(peeked))
		}
	}
}

func TestSNIReadsHandBuiltHello(t *testing.T) {
	hello := buildClientHello(t, "handbuilt.test", 0, nil)

	sni, _, err := readClientHelloSNI(bytes.NewReader(hello), maxHeadBytes)
	if err != nil {
		t.Fatalf("readClientHelloSNI: %v", err)
	}
	if sni != "handbuilt.test" {
		t.Fatalf("parsed SNI %q, want %q", sni, "handbuilt.test")
	}
}

func TestSNIRefusesGarbage(t *testing.T) {
	cases := map[string][]byte{
		"plaintext http": []byte("GET / HTTP/1.1\r\nHost: whatever.test\r\n\r\n"),
		"tls alert":      {0x15, 0x03, 0x03, 0x00, 0x02, 0x01, 0x00},
		"tls app data":   {0x17, 0x03, 0x03, 0x00, 0x01, 0x00},
		"server hello":   {0x16, 0x03, 0x03, 0x00, 0x04, 0x02, 0x00, 0x00, 0x00},
		"all zeroes":     make([]byte, 64),
	}

	for name, garbage := range cases {
		sni, _, err := readClientHelloSNI(bytes.NewReader(garbage), maxHeadBytes)
		if err == nil {
			t.Fatalf("%s: parse must fail, got SNI %q", name, sni)
		}
		if errors.Is(err, ErrSNIAbsent) {
			t.Fatalf("%s: garbage is not an absent SNI, it is a parse failure", name)
		}
	}
}

func TestSNIRefusesTruncatedHello(t *testing.T) {
	hello := captureClientHello(t, tlsClientConfig("truncated.test"))

	for _, cut := range []int{1, 4, 9, 40, len(hello) / 2} {
		if _, _, err := readClientHelloSNI(bytes.NewReader(hello[:cut]), maxHeadBytes); err == nil {
			t.Fatalf("a hello cut to %d bytes must not parse", cut)
		}
	}
}

func TestSNIRefusesOversizedHello(t *testing.T) {
	// One record whose declared body alone passes the budget: refused before
	// a byte of body is read.
	var header [5]byte
	header[0] = tlsRecordHandshake
	header[1], header[2] = 0x03, 0x01
	binary.BigEndian.PutUint16(header[3:5], 0xFFFF)
	_, _, err := readClientHelloSNI(bytes.NewReader(header[:]), maxHeadBytes)
	if !errors.Is(err, errSNIOversized) {
		t.Fatalf("a %d-byte record must be refused as oversized, got %v", 0xFFFF, err)
	}

	// A hello whose handshake header claims more than the budget: the first
	// record fits inside it, and the refusal lands when the continuation
	// record arrives -- before a byte of that continuation is read.
	oversized := make([]byte, 5+65530)
	oversized[0] = tlsRecordHandshake
	oversized[1], oversized[2] = 0x03, 0x01
	binary.BigEndian.PutUint16(oversized[3:5], 65530)
	oversized[5] = tlsHandshakeClientHello
	oversized[6], oversized[7], oversized[8] = 0x01, 0x00, 0x00 // claims 0x010000 bytes
	oversized = append(oversized, tlsRecordHandshake, 0x03, 0x03, 0x00, 0x01)
	_, _, err = readClientHelloSNI(bytes.NewReader(oversized), maxHeadBytes)
	if !errors.Is(err, errSNIOversized) {
		t.Fatalf("a hello claiming %d bytes must be refused as oversized, got %v", 0x10000, err)
	}
}

func TestSNIRefusesEmptyAndMissingHostEntries(t *testing.T) {
	// An SNI extension whose list carries no host_name entry at all is
	// malformed, not absent: the extension's presence promises a name.
	broken := buildClientHello(t, "", 0x0000, []byte{0x00, 0x04, 0x07, 0x00, 0x00, 0x00})
	if _, _, err := readClientHelloSNI(bytes.NewReader(broken), maxHeadBytes); err == nil {
		t.Fatal("a server_name list with no host_name entry must be refused")
	}

	// An empty host_name entry: equally malformed, and dangerous to read as
	// "" (which the router would lowercase into a miss and treat as absent).
	empty := buildClientHello(t, "", 0x0000, []byte{0x00, 0x03, 0x00, 0x00, 0x00})
	if _, _, err := readClientHelloSNI(bytes.NewReader(empty), maxHeadBytes); err == nil {
		t.Fatal("an empty host_name entry must be refused")
	}
}

func TestSNIKeepsTrailingBytesForReplay(t *testing.T) {
	// A client may pack its next handshake message into the same record that
	// finishes the hello. Those bytes are inside a record the parser has to
	// read to the end of, so they are consumed -- and they must come back
	// untouched, because the TLS terminator replays everything the parser
	// touched. (Bytes after the last record are a different matter: the
	// parser stops there, so they are never consumed at all.)
	hello := buildClientHello(t, "trailing.test", 0, nil)
	hs := hello[5:]

	rec := make([]byte, 0, len(hs)+4+4)
	rec = append(rec, tlsRecordHandshake, 0x03, 0x01)
	rec = append(rec, byte((len(hs)+4)>>8), byte(len(hs)+4))
	rec = append(rec, hs...)
	pipelined := append(rec, []byte("TAIL")...)

	sni, peeked, err := readClientHelloSNI(bytes.NewReader(pipelined), maxHeadBytes)
	if err != nil {
		t.Fatalf("readClientHelloSNI: %v", err)
	}
	if sni != "trailing.test" {
		t.Fatalf("parsed SNI %q, want %q", sni, "trailing.test")
	}
	if !bytes.Equal(peeked, pipelined) {
		t.Fatalf("peeked must include the trailing bytes: got %d, want %d", len(peeked), len(pipelined))
	}
}

// TestSNIReplayCompletesRealHandshake is the round trip the replay contract
// exists for: the bytes the peek consumed, put back on the front of the
// stream, let a REAL tls.Server finish a REAL handshake with the client that
// sent them -- and the server side of that handshake reports the SNI the
// parser found.
func TestSNIReplayCompletesRealHandshake(t *testing.T) {
	client, rawServer := startTLSClient(t, tlsClientConfig("roundtrip.test"))

	handshakeErr := make(chan error, 1)
	go func() { handshakeErr <- client.Handshake() }()

	sni, peeked, err := readClientHelloSNI(rawServer, maxHeadBytes)
	if err != nil {
		t.Fatalf("readClientHelloSNI: %v", err)
	}
	if sni != "roundtrip.test" {
		t.Fatalf("parsed SNI %q, want %q", sni, "roundtrip.test")
	}

	// The terminator: tls.Server over a replay conn, exactly what
	// terminateWithServerCert builds.
	tlsCfg, err := LoadTLSConfig("", "")
	if err != nil {
		t.Fatalf("loading the snakeoil test certificate: %v", err)
	}
	replay := newReplayConn(conn.Wrap(rawServer, "pub"), peeked, rawServer)
	tlsSrv := tls.Server(replay, tlsCfg)

	serverErr := make(chan error, 1)
	go func() { serverErr <- tlsSrv.Handshake() }()

	select {
	case err := <-handshakeErr:
		if err != nil {
			t.Fatalf("client handshake over the replayed stream failed: %v", err)
		}
	case <-time.After(publicTimeout):
		t.Fatal("the client handshake never finished")
	}
	select {
	case err := <-serverErr:
		if err != nil {
			t.Fatalf("server handshake over the replayed stream failed: %v", err)
		}
	case <-time.After(publicTimeout):
		t.Fatal("the server handshake never finished")
	}

	// The SNI the parser extracted is the SNI the TLS stack saw.
	if got := tlsSrv.ConnectionState().ServerName; got != "roundtrip.test" {
		t.Fatalf("the terminated handshake saw SNI %q, want %q", got, "roundtrip.test")
	}
}

// ---------------------------------------------------------------------------
// 7-A: https listener routing

// testTLSConfig returns the server's snakeoil terminator config (assets only
// load under -tags debug, which this suite requires).
func testTLSConfig(t *testing.T) *tls.Config {
	t.Helper()

	cfg, err := LoadTLSConfig("", "")
	if err != nil {
		t.Fatalf("loading the snakeoil test certificate: %v", err)
	}
	return cfg
}

// startHTTPSHandler runs the real httpsConnHandler on the server end of a
// fresh loopback pair and returns the public client end.
func startHTTPSHandler(t *testing.T, tlsCfg *tls.Config) *net.TCPConn {
	t.Helper()

	publicClient, publicServer := tcpPair(t)
	go httpsConnHandler(conn.Wrap(publicServer, "pub"), tlsCfg)
	return publicClient
}

// The StartProxy assertions below reuse the package fixture readStartProxy
// (policy_test.go); the head assertions reuse readHead.

func TestSNIRoutesAgentTerminatedTunnelVerbatim(t *testing.T) {
	setupTestRegistry(t)
	ctl := testControl(t, "")
	tun := registerTestTunnel(t, ctl, msg.ReqTunnel{
		Protocol:       msg.ProtoHTTPS,
		Hostname:       "agent.test",
		TLSTermination: msg.TLSTerminationAgent,
	})
	agentConn := armHTTPAgent(t, ctl)

	// A real visitor's hello: the exact bytes the peek must hand back.
	hello := captureClientHello(t, tlsClientConfig("agent.test"))

	publicClient := startHTTPSHandler(t, testTLSConfig(t))
	if _, err := publicClient.Write(hello); err != nil {
		t.Fatalf("failed to write the ClientHello: %v", err)
	}

	startProxy := readStartProxy(t, agentConn, "sni-routing agent")
	if startProxy.Url != tun.url {
		t.Fatalf("StartProxy names %q, want the agent-terminated endpoint %q", startProxy.Url, tun.url)
	}

	// After the StartProxy framing, the hello must arrive byte for byte --
	// the zero-knowledge contract on the wire: the server's terminator never
	// saw these bytes, the agent's own TLS stack will.
	if err := agentConn.SetReadDeadline(time.Now().Add(publicTimeout)); err != nil {
		t.Fatalf("failed to set a read deadline: %v", err)
	}
	got := make([]byte, len(hello))
	if _, err := io.ReadFull(agentConn, got); err != nil {
		t.Fatalf("the ClientHello never reached the agent verbatim: %v", err)
	}
	if !bytes.Equal(got, hello) {
		t.Fatal("the bytes reaching the agent differ from the visitor's ClientHello")
	}
}

func TestSNIRoutesEdgeTunnelThroughHostPath(t *testing.T) {
	setupTestRegistry(t)
	ctl := testControl(t, "")
	registerTestTunnel(t, ctl, msg.ReqTunnel{Protocol: msg.ProtoHTTPS, Hostname: "edge.test"})
	agentConn := armHTTPAgent(t, ctl)

	publicClient := startHTTPSHandler(t, testTLSConfig(t))

	// The visitor terminates at the server (snakeoil), then the Host header
	// routes -- the pre-SNI path, now reached through the peek.
	client := tls.Client(publicClient, tlsClientConfig("edge.test"))
	if err := client.SetDeadline(time.Now().Add(publicTimeout)); err != nil {
		t.Fatalf("failed to set a deadline: %v", err)
	}
	head := "GET / HTTP/1.1\r\nHost: edge.test\r\n\r\n"
	if _, err := client.Write([]byte(head)); err != nil {
		t.Fatalf("failed to write the request: %v", err)
	}

	readStartProxy(t, agentConn, "sni-routing agent")
	if got := readHead(t, agentConn, "edge-terminated agent"); got != head {
		t.Fatalf("the agent received %q, want the request head verbatim", got)
	}
}

func TestSNINoSNITerminatesWithServerCert(t *testing.T) {
	setupTestRegistry(t) // no tunnels at all: any Host must 404

	publicClient := startHTTPSHandler(t, testTLSConfig(t))

	// InsecureSkipVerify with no ServerName: Go sends no server_name
	// extension at all.
	client := tls.Client(publicClient, &tls.Config{InsecureSkipVerify: true, MaxVersion: tls.VersionTLS12})
	if err := client.SetDeadline(time.Now().Add(publicTimeout)); err != nil {
		t.Fatalf("failed to set a deadline: %v", err)
	}
	if _, err := client.Write([]byte("GET / HTTP/1.1\r\nHost: nobody.test\r\n\r\n")); err != nil {
		t.Fatalf("failed to write the request: %v", err)
	}

	resp, err := http.ReadResponse(bufio.NewReader(client), nil)
	if err != nil {
		t.Fatalf("no response from the server-cert terminator: %v", err)
	}
	defer resp.Body.Close()
	body, _ := io.ReadAll(resp.Body)
	if resp.StatusCode != 404 {
		t.Fatalf("status %d, want 404-by-Host (body %q)", resp.StatusCode, body)
	}
	if !strings.Contains(string(body), "nobody.test") {
		t.Fatalf("the 404 body must name the Host, got %q", body)
	}
}

func TestSNIHostReachingAgentTunnelOnTerminatedConnGets421(t *testing.T) {
	for _, sni := range []string{"", "edge.test"} {
		name := "no SNI"
		if sni != "" {
			name = "SNI " + sni
		}
		t.Run(name, func(t *testing.T) {
			setupTestRegistry(t)
			ctl := testControl(t, "")
			registerTestTunnel(t, ctl, msg.ReqTunnel{
				Protocol:       msg.ProtoHTTPS,
				Hostname:       "agent.test",
				TLSTermination: msg.TLSTerminationAgent,
			})
			if sni != "" {
				registerTestTunnel(t, ctl, msg.ReqTunnel{Protocol: msg.ProtoHTTPS, Hostname: "edge.test"})
			}

			publicClient := startHTTPSHandler(t, testTLSConfig(t))

			cfg := &tls.Config{InsecureSkipVerify: true, MaxVersion: tls.VersionTLS12}
			if sni != "" {
				cfg.ServerName = sni
			}
			client := tls.Client(publicClient, cfg)
			if err := client.SetDeadline(time.Now().Add(publicTimeout)); err != nil {
				t.Fatalf("failed to set a deadline: %v", err)
			}
			if _, err := client.Write([]byte("GET / HTTP/1.1\r\nHost: agent.test\r\n\r\n")); err != nil {
				t.Fatalf("failed to write the request: %v", err)
			}

			resp, err := http.ReadResponse(bufio.NewReader(client), nil)
			if err != nil {
				t.Fatalf("no 421 response: %v", err)
			}
			defer resp.Body.Close()
			// The ReadAll error is the assertion: a 421 whose Content-Length
			// disagrees with the bytes written (the helper once sent the bare
			// hostname while announcing the sentence's length) reads as an
			// unexpected EOF here, and a body-contains check alone passes on
			// the partial bytes.
			body, err := io.ReadAll(resp.Body)
			if err != nil {
				t.Fatalf("the 421 body did not read to its Content-Length: %v", err)
			}
			if resp.StatusCode != 421 {
				t.Fatalf("status %d, want 421 Misdirected Request (body %q)", resp.StatusCode, body)
			}
			if !strings.Contains(string(body), "agent.test") {
				t.Fatalf("the 421 body must name the endpoint, got %q", body)
			}
		})
	}
}

func TestSNIGarbageOnHTTPSListenerNeverReachesAgent(t *testing.T) {
	setupTestRegistry(t)
	ctl := testControl(t, "")
	registerTestTunnel(t, ctl, msg.ReqTunnel{Protocol: msg.ProtoHTTPS, Hostname: "agent.test"})
	agentConn := armHTTPAgent(t, ctl)

	publicClient := startHTTPSHandler(t, testTLSConfig(t))
	// Plaintext HTTP into the TLS port: the peek fails, the connection is
	// treated as SNI-absent, and the TLS terminator (not the router) answers
	// it. Whatever happens, no agent may be dispatched.
	if _, err := publicClient.Write([]byte("GET / HTTP/1.1\r\nHost: agent.test\r\n\r\n")); err != nil {
		t.Fatalf("failed to write the garbage: %v", err)
	}

	if err := publicClient.SetReadDeadline(time.Now().Add(publicTimeout)); err != nil {
		t.Fatalf("failed to set a read deadline: %v", err)
	}
	buf := make([]byte, 512)
	for {
		if _, err := publicClient.Read(buf); err != nil {
			break // EOF or reset: the connection is down, which is the point
		}
	}

	// No StartProxy may have been written: the dead stream stopped at the edge.
	if err := agentConn.SetReadDeadline(time.Now().Add(250 * time.Millisecond)); err != nil {
		t.Fatalf("failed to set a read deadline: %v", err)
	}
	one := make([]byte, 1)
	if n, err := agentConn.Read(one); n > 0 || err == nil {
		t.Fatal("garbage on the https listener must not reach an agent")
	}
}

// TestSNIAgentTerminatedWithPolicyStaysRaw is the zero-knowledge invariant
// with teeth: the tunnel carries an on_http_request policy (which on an edge
// tunnel would install rewriter hooks over the public leg), yet the
// ClientHello must still reach the agent untouched -- the policy's http
// phases have nothing to read here, and the join must stay raw regardless.
func TestSNIAgentTerminatedWithPolicyStaysRaw(t *testing.T) {
	setupTestRegistry(t)
	ctl := testControl(t, "")
	tun := registerTestTunnel(t, ctl, msg.ReqTunnel{
		Protocol:       msg.ProtoHTTPS,
		Hostname:       "agent.test",
		TLSTermination: msg.TLSTerminationAgent,
		TrafficPolicy: &policy.TrafficPolicy{
			OnHTTPRequest: []*policy.Action{
				policyActionConfig("log", map[string]interface{}{"metadata": map[string]interface{}{"note": "raw-path-guard"}}),
			},
		},
	})
	if tun.policy == nil {
		t.Fatal("the test tunnel must carry a compiled policy for this assertion to mean anything")
	}
	agentConn := armHTTPAgent(t, ctl)

	hello := captureClientHello(t, tlsClientConfig("agent.test"))
	publicClient := startHTTPSHandler(t, testTLSConfig(t))
	if _, err := publicClient.Write(hello); err != nil {
		t.Fatalf("failed to write the ClientHello: %v", err)
	}

	readStartProxy(t, agentConn, "policy-carrying agent tunnel")

	if err := agentConn.SetReadDeadline(time.Now().Add(publicTimeout)); err != nil {
		t.Fatalf("failed to set a read deadline: %v", err)
	}
	got := make([]byte, len(hello))
	if _, err := io.ReadFull(agentConn, got); err != nil {
		t.Fatalf("the ClientHello never reached the agent: %v", err)
	}
	if !bytes.Equal(got, hello) {
		t.Fatal("a policy-carrying agent tunnel must still pass the stream through untouched")
	}
}

// TestSNIForwardChainToPlainTerminusStaysRaw guards the corner the marker on
// serveAgentTLS's public conn exists for: an agent-terminated entry endpoint
// whose forward_to chain lands on a plain-HTTP terminus that carries an
// on_http_request policy. The chain's terminus has no TLS key for the stream
// either -- the ciphertext was born on the entry endpoint's SNI route -- so
// its join must stay raw DESPITE the policy: the deny below must not fire, and
// the ClientHello must reach the agent byte for byte. A rewriter hook pointed
// at this stream would scan TLS records for an HTTP head and find none; the
// hello would stall in the hook's buffer and never be delivered.
func TestSNIForwardChainToPlainTerminusStaysRaw(t *testing.T) {
	setupTestRegistry(t)
	ctl := testControl(t, "")

	// The terminus: a plain-HTTP internal endpoint whose policy would deny
	// every request -- if the connection ever got parsed as HTTP, which is
	// precisely what must not happen here.
	internal := registerTestTunnel(t, ctl, msg.ReqTunnel{
		Protocol: "http", Binding: msg.BindingInternal, Hostname: "svc.internal",
		TrafficPolicy: &policy.TrafficPolicy{
			OnHTTPRequest: []*policy.Action{policyActionConfig("deny", map[string]interface{}{"status_code": 403})},
		},
	})
	if internal.policy == nil {
		t.Fatal("the internal terminus must carry a compiled policy for this assertion to mean anything")
	}
	// The entry: agent-terminated, forwards, and deliberately carries no
	// policy of its own, so the terminus's policy is the one join sees.
	registerTestTunnel(t, ctl, msg.ReqTunnel{
		Protocol:       msg.ProtoHTTPS,
		Hostname:       "entry.test",
		TLSTermination: msg.TLSTerminationAgent,
		ForwardTo:      internal.url,
	})
	agentConn := armHTTPAgent(t, ctl)

	hello := captureClientHello(t, tlsClientConfig("entry.test"))
	publicClient := startHTTPSHandler(t, testTLSConfig(t))
	if _, err := publicClient.Write(hello); err != nil {
		t.Fatalf("failed to write the ClientHello: %v", err)
	}

	// The chain landed on the internal terminus: its url names the proxy conn.
	startProxy := readStartProxy(t, agentConn, "the forward chain's agent")
	if startProxy.Url != internal.url {
		t.Fatalf("StartProxy names %q, want the forward target %q", startProxy.Url, internal.url)
	}

	if err := agentConn.SetReadDeadline(time.Now().Add(publicTimeout)); err != nil {
		t.Fatalf("failed to set a read deadline: %v", err)
	}
	got := make([]byte, len(hello))
	if _, err := io.ReadFull(agentConn, got); err != nil {
		t.Fatalf("the ClientHello never reached the agent across the forward chain: %v", err)
	}
	if !bytes.Equal(got, hello) {
		t.Fatal("the terminus's policy parsed the stream: the hello must cross the chain untouched")
	}
}
